version: '3.8'

services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    network_mode: host
    volumes:
      - ./frps.toml:/etc/frps.toml
      - ./frps_logs:/var/log/frps
    restart: unless-stopped
